### ISSUE TITLE
CI support

### ISSUE THREAD

**Issue by fatihi** [fatihi/fiveringsdb#11]
Add a CI for automatic testing and deployment

**Comment by fatihi** [comment]
I'd suggest we use https://www.appveyor.com/

**Comment by fatihi** [comment]
* https://elanderson.net/2018/08/deploying-an-asp-net-core-application-to-digitalocean/

**Comment by Fuzzylog1cza** [comment]
For now I've put this on travis-ci. See https://travis-ci.org/fatihi/fiveringsdb. Can we consider this issue closed until we need to revisit it for more/better features?

Technically we should have this autodeploying once stuff hits master but lets get a working app first.
