### ISSUE TITLE
Setup adr

### ISSUE THREAD

**Issue by programming-wolf** [fatihi/fiveringsdb#15]
We should (early) document some architectural decisions, like chosen programming language/framework, database, code style, etc.

**Comment by fatihi** [comment]
Where to? Into the Wiki?

**Comment by programming-wolf** [comment]
No, directly into the repository with madr. 
I already created a branch and started with the very basics. I wanted to ask which technologies we use and why, so that I can create the records. :)

**Comment by fatihi** [comment]
Right now we have set up dotnet core, travis and (soon) docker. For the database we wanted to use postgres and I think for now that's it, right?

**Comment by programming-wolf** [comment]
Sounds good. I’ll do that today.

**Comment by programming-wolf** [comment]
Fixed with #20
