### ISSUE TITLE
Influence Cost should not be nullable type

### ISSUE THREAD

**Issue by degoeym** [fatihi/fiveringsdb#26]
I wanna say if I recall the conversations correctly that influence values shouldn't be nullable. If the card can't be splashed the value would be 0.

https://github.com/fatihi/fiveringsdb/blob/a5df0f429c154926d1bcfe8ffe0bab97703495df/FiveRingsDb/Entities/CharacterCard.cs#L13

**Comment by fatihi** [comment]
I'm not sure, I just made it nullable because the current API doesn't show a value at all for cards like duty. If we change it to non-nullable, it needs to be changed on the other card types as well
