### ISSUE TITLE
Add enum for keywords

### ISSUE THREAD

**Issue by programming-wolf** [fatihi/fiveringsdb#28]
Having  an enum for keywords would make things easier for others as it would help to maintain a stable API. It also makes sense as we have enum for traits. 

covert, restricted, limited, pride, courtesy, sincerity, no attachments, ancestral, composure (and now “disguised TRAIT”))

**Comment by degoeym** [comment]
This shouldn't be hard to implement. I can likely get on this at some point unless @fatihi wants to wrap it up as part of his current work.

**Comment by programming-wolf** [comment]
I'll take care of this this weekend (hopefully), maybe in pair-programming with @fatihi or alone. :)
