### ISSUE TITLE
Client Rewrite

### ISSUE THREAD

**Issue by Fuzzylog1cza** [fatihi/fiveringsdb#4]
After #3 has been completed a client rewrite needs to be addressed. Current client is in Vue which needs to be considered based on our existing contributors.

Proposals have been raised for switching to React.

Ideally as many clients as we want can be spun off if the API can service their needs e.g. Jigoku etc.

**Comment by NoahTheDuke** [comment]
How many views actually exist right now? React would be fun but is it overkill?

**Comment by Fuzzylog1cza** [comment]
Right now the client app is fairly simple. Vue was a good fit for it and I'm happy to maintain it. 

This issue is in place for community members who may want to try their hand at redoing the app. React is still the most downloaded ui framework so it's understandable that it's been proposed as a potential framework for a rewrite.

There is a lot of other stuff to get done before we get here though.
