### ISSUE TITLE
Open modal when clicked on card

### ISSUE THREAD

**Issue by fatihi** [fatihi/fiveringsdb#47]

**Comment by programming-wolf** [comment]
I think clicking on a card should forward to the card page. We’ve got the hover effect for the first look.

**Comment by fatihi** [comment]
Didn't really think about it. It was just the behavior in the current fiveringsdb, so I created an issue. 
I think on PC that's fine but on mobile you might want to have the modal, since there is no hovering on mobile.

**Comment by programming-wolf** [comment]
My preference on mobile would be to be forwarded to the detail site as well. I don’t like modals on mobile. Data will be loaded anyway so a forward to a new site would be ok, to my mind.

**Comment by fatihi** [comment]
I'm fine with that as well. Then I'll just close this issue and if any people request this feature, we can discuss it again.
